use MotiAdviser;

INSERT INTO `Class` VALUES 
(NULL,'CIS 105 Explorations in Computing','',4,Null,Null),
(NULL,'CIS 110 Fluency with Information Technology','',4,Null,Null),
(NULL,'CIS 111 Introduction to Web Programming','',4,Null,Null),
(NULL,'CIS 115 Multimedia Web Programming','',4,Null,Null),
(NULL,'CIS 122 Intro to Programming and Problem Solving','',4,Null,Null),
(NULL,'CIS 199 Making and Breaking Codes','',4,Null,Null),
(NULL,'CIS 210 Computer Science I','',4,Null,Null),
(NULL,'CIS 211 Computer Science II','',4,Null,Null),
(NULL,'CIS 212 Computer Science III','',4,Null,Null),
(NULL,'CIS 313 Intermediate to Data Structures','',4,Null,Null),
(NULL,'CIS 314 Computer Organization','',4,Null,Null),
(NULL,'CIS 315 Intermediate Algorithms','',4,Null,Null),
(NULL,'CIS 330 C/C++ & Unix','',4,Null,Null),
(NULL,'CIS 407 Seminar on CIS Careers and Internships','',4,Null,Null),
(NULL,'CIS 415 Operating Systems','',4,Null,Null),
(NULL,'CIS 425 Principles of Programming Languages','',4,Null,Null),
(NULL,'CIS 407 Programming Competition','',4,Null,Null),
(NULL,'CIS 410 Parallel Computing','',4,Null,Null),
(NULL,'CIS 410 Probabilistic Methods','',4,Null,Null),
(NULL,'CIS 410 Scientific Visualization','',4,Null,Null),
(NULL,'CIS 410 Secure Development','',4,Null,Null),
(NULL,'CIS 420 Automata Theory','',4,Null,Null),
(NULL,'CIS 422 Software Methodology','',4,Null,Null),
(NULL,'CIS 423 Software Methodologies II','',4,Null,Null),
(NULL,'CIS 427 Introduction to Logic','',4,Null,Null),
(NULL,'CIS 432 Intro to Computer Networks','',4,Null,Null),
(NULL,'CIS 433 Computer & Network Security','',4,Null,Null),
(NULL,'CIS 445 Modeling and Simulation','',4,Null,Null),
(NULL,'CIS 451 Database Processing','',4,Null,Null),
(NULL,'CIS 452 Database issues','',4,Null,Null),
(NULL,'CIS 453 Data Mining','',4,Null,Null),
(NULL,'CIS 454 Bioinformatics','',4,Null,Null),
(NULL,'CIS 471 Introduction to Artificial Intelligence','',4,Null,Null),
(NULL,'CIS 472 Machine Learning','',4,Null,Null),
(NULL,'CIS 490 Computer Ethics','',4,Null,Null),
(NULL,'CIS 610 New Networking Architectures','',4,Null,Null),
(NULL,'CIS 610 Teaching Effectiveness Seminar','',4,Null,Null),
(NULL,'CIS 621 Algorithms and Complexity','',4,Null,Null),
(NULL,'CIS 624 Structure of Programming Languages','',4,Null,Null),
(NULL,'CIS 630 Introduction to Artificial Intelligence','',4,Null,Null),
(NULL,'CIS 632 Machine Learning','',4,Null,Null),
(NULL,'CIS 650 Computer Ethics','',4,Null,Null),
(NULL,'MATH 231 Elements of Discrete Mathematics I','',4,Null,Null),
(NULL,'MATH 232 Elements of Discrete Mathematics II','',4,Null,Null),
(NULL,'MATH 233 Elements of Discrete Mathematics III','',4,Null,Null),
(NULL,'MATH 251 Calculus I','',4,Null,Null),
(NULL,'MATH 252 Calculus II','',4,Null,Null),
(NULL,'MATH 253 Calculus III','',4,Null,Null),
(NULL,'MATH 261 Calculus with Theory I','',4,Null,Null),
(NULL,'MATH 262 Calculus with Theory II','',4,Null,Null),
(NULL,'MATH 263 Calculus with Theory III','',4,Null,Null),
(NULL,'MATH 246 Calculus for the Biological Sciences I','',4,Null,Null),
(NULL,'MATH 247 Calculus for the Biological Sciences II','',4,Null,Null),
(NULL,'MATH 341 Elementary Linear Algebra','',4,Null,Null),
(NULL,'MATH 343 Statistical Models/Methods','',4,Null,Null),
(NULL,'MATH 425 Statistical Methods I','',4,Null,Null),
(NULL,'PHYS 201 General Physics I','',4,Null,Null),
(NULL,'PHYS 202 General Physics II','',4,Null,Null),
(NULL,'PHYS 203 General Physics III','',4,Null,Null),
(NULL,'PHYS 251 Foundations of Physics I','',4,Null,Null),
(NULL,'PHYS 252 Foundations of Physics II','',4,Null,Null),
(NULL,'PHYS 253 Foundations of Physics III','',4,Null,Null),
(NULL,'CH 221 General Chemistry I','',4,Null,Null),
(NULL,'CH 222 General Chemistry II','',4,Null,Null),
(NULL,'CH 223 General Chemistry III','',4,Null,Null),
(NULL,'CH 224H Honors General Chemistry I','',4,Null,Null),
(NULL,'CH 225H Honors General Chemistry II','',4,Null,Null),
(NULL,'CH 226H Honors General Chemistry III','',4,Null,Null),

(NULL,'CH 111 Introduction to Chemical Principles','',4,Null,Null),
(NULL,'CH 113 The Chemistry of Sustainability','',4,Null,Null),
(NULL,'CH 221 General Chemistry','',4,Null,Null),
(NULL,'CH 224 Honors General Chemistry','',4,Null,Null),
(NULL,'BI 211 General Biology I','',4,Null,Null),
(NULL,'BI 212 General Biology II','',4,Null,Null),
(NULL,'BI 212 General Biology III','',4,Null,Null),

(NULL,'PSY 201 Mind and Brain','',4,Null,Null),
(NULL,'PSY 202 Mind and Society','',4,Null,Null),
(NULL,'PSY 304 Biopsychology','',4,Null,Null),
(NULL,'PSY 330 Thinking','',4,Null,Null),
(NULL,'PSY 348 Music and the Brain','',4,Null,Null),

(NULL,'GEOG 141 The Natural Environment','',4,Null,Null),
(NULL,'GEOG 321 Climatology','',4,Null,Null),
(NULL,'GEOG 322 Geomorphology','',4,Null,Null),
(NULL,'GEOG 323 Biogeography','',4,Null,Null),

(NULL,'GEOL 201 Earth Interior Heat and Dynamics','',4,Null,Null),
(NULL,'GEOL 202 Earth Surface and Environmental Geology','',4,Null,Null),
(NULL,'GEOL 203 Evolution of the Earth','',4,Null,Null),


(NULL,'WR 121 College Composition I','',4,Null,Null),
(NULL,'WR 122 College Composition II','',4,Null,Null),
(NULL,'WR 123 College Composition III','',4,Null,Null),
(NULL,'WR 320 Scientific and Technical Writing','',4,Null,Null),
(NULL,'WR 321 Business Communications','',4,Null,Null);





INSERT INTO `DependentClass` VALUES 
(8,7,'N'),
(9,8,'N'),
(10,9,'N'),
(11,9,'N'),
(35,9,'N'),
(12,10,'N'),
(18,10,'N'),
(19,10,'N'),
(20,10,'N'),
(21,10,'N'),
(23,10,'N'),
(29,10,'N'),
(29,12,'N'),
(13,11,'N'),
(24,23,'N'),
(22,12,'N'),
(34,12,'N'),
(33,12,'N'),
(16,12,'N'),
(28,12,'N'),
(28,13,'N'),
(15,13,'N'),
(26,13,'N'),
(38,22,'N'),
(25,16,'N'),
(27,15,'N'),
(40,15,'N'),
(41,26,'N'),
(44,43,'N'),
(45,44,'N'),
(47,46,'N'),
(48,47,'N'),
(50,49,'N'),
(51,50,'N'),
(53,52,'N'),
(54,46,'N'),
(54,48,'N'),
(55,47,'N'),
(58,57,'N'),
(59,58,'N'),
(61,60,'N'),
(62,61,'N'),
(64,63,'N'),
(65,64,'N'),
(66,46,'Y'),
(66,49,'Y'),
(67,66,'N'),
(68,67,'N'),
(73,66,'Y'),
(73,69,'Y'),
(73,70,'Y'),
(73,71,'Y'),
(74,73,'N'),
(75,73,'N'),
(82,81,'N'),
(83,81,'N'),
(84,81,'N'),
(87,85,'N'),
(89,88,'N'),
(90,88,'N'),
(91,89,'Y'),
(91,90,'Y'),
(92,89,'Y'),
(92,90,'Y');



INSERT INTO `Major` VALUES 
(Null,'CIS','Business Information Systems'),
(Null,'CIS','Computational Science'),
(Null,'CIS','Computer Networks'),
(Null,'CIS','Computer Security'),
(Null,'CIS','Database and Informatics'),
(Null,'CIS','Foundations'),
(Null,'CIS','Software Development');

INSERT INTO `RequireType` VALUES 
(Null,'Lower-Division Core Courses',20),
(Null,'Upper-Division Core Courses',28),
(Null,'Mathematics Requirements 1',8),
(Null,'Mathematics Requirements 2',8),

(Null,'Science Requirements',12),
(Null,'Colleage Writing',8),
(Null,'Writing Core Course',4),
(Null,'BIS Track Requirements 1',12),
(Null,'BIS Track Requirements 2',8),
(Null,'BIS Track Requirements 3',4);


INSERT INTO `GraduateRule` VALUES 
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10);

INSERT INTO `GroupsOfType` VALUES 
(Null,1,'N'), /*Upper-Division Core Courses; one group*/
(Null,2,'N'), /*Upper-Division Core Courses; one group*/
(Null,3,'Y'), /*Mathematics Requirements 1; 3 groups*/
(Null,3,'Y'),
(Null,3,'Y'),
(Null,4,'N');/*Mathematics Requirements 1; 1 groups*/



INSERT INTO `ClassesOfGroup` VALUES 
(1,7,'N','Y'),
(1,8,'N','Y'),
(1,9,'N','Y'),
(1,43,'N','Y'),
(1,44,'N','Y'),

(2,10,'N','Y'),
(2,11,'N','Y'),
(2,12,'N','Y'),
(2,13,'N','Y'),
(2,44,'N','Y'),
(2,15,'N','Y'),
(2,16,'N','Y'),
(2,23,'N','Y'),

(3,46,'N','Y'),
(3,47,'N','Y'),
(4,49,'N','Y'),
(4,50,'N','Y'),
(5,52,'N','Y'),
(5,53,'N','Y'),

(6,45,'Y','Y'),
(6,48,'Y','Y'),
(6,54,'Y','Y'),
(6,56,'Y','Y');

